Return file version
r-box/boxr pull request #181
Opened 2020-09-14 18:49 UTC by alexbrodersen

The file version_id can be useful for tracking versions but is not available in box_previous_versions for the currently "active" version of the file. This pull request updates box_ls() and the s3 as.data.frame method to include the version_id, as well as alters the name of the value of the current "version" to "version_no".

2020-09-15 13:39 UTC, nathancday commented
Thanks for the PR. I like you idea of mirroring the behavior of `box_previous_versions` and the proposed name changes sound good.

Do you have a specific instance were you want to use version_id instead of version_no?

I've been working on adding a function, `box_file_version()` that uses file IDs to do something like this with version_no results. As part of that I've have been re-considering what we return our of `box_previous_versions()` and my thinking was that version_no alone was enough, but maybe not :)

2020-09-16 14:06 UTC, nathancday commented
Got it. Paired with a file_id, either a version_id or version_no is enough. Numbers are inferred, but the Box web-app does that too. I've personally found it humanly easier to work with version_no, but I like your idea of having both easily available to users.

2020-09-16 15:41 UTC, alexbrodersen commented
I agree, especially if using both boxr and Web App, the version_no is more straightforward to work with.

I do think both should be provided.

One case where the version_id matters is (at least in the enterprise version) is the URL for file version.

This has the form

https://{company_name}.app.box.com/file/{file_id}?sb=/activity/versions/{version_id}

and as far as I know version_no can't be used in this way.

2020-09-21 00:12 UTC, ijlyttle commented
Let me put my own spin on `version_no`: this is a construct only of the {boxr} package, and is completely independent of the Box API, which knows only `file_version_id`. In other words, I agree that both are important.

We are currently working on a successor to `box_previous_versions()`, called `box_version_history()`.

One of the things I might like to implement in `box_version_history()` is to return a column `version_no`, rather than a character column ,`version` with values `"V1"`, `"V2"`, etc. - so this sounds like a good fit.  One of the neat things about introducing a new name is that we can get away with changing the API :) 

I think we should keep the `version` variable in the `as.data.frame()` method because this could be a breaking change for someone otherwise. I don't know how to deprecate a variable in a return object, maybe the least-bad thing would be to keep them both, awkward as that may be. Thoughts?

In short, I think that it would be good to standardize on the use of `version_no` within {boxr}, and this is a step in that direction.

There's another PR that I want to get wrapped-up first, then we may have some specific suggestions for this one.

2020-09-21 00:17 UTC, ijlyttle commented
Another question - the use of `x$etag` predates my involvement. I have read around a bit ([google search](https://www.google.com/search?q=boxr+api+etag)), and I have not found anything that suggests that this is a rock-solid proxy for version number.

Of course, it was done this way for a reason - I would like to feel good about the reason while we have the question on the floor.

2020-09-21 00:48 UTC, ijlyttle commented
Finally (for now), welcome @alexbrodersen!

So that you can feel fully a part of the fun: I had a quick look through our code, and see that we use refer to `file_version_id` and `version_id`, although Box uses `file_version_id`.

As a first thought, it might be easiest for {boxr} to standardize on `version_id`.

2020-09-21 15:15 UTC, alexbrodersen commented
@ijlyttle Regarding depreciating a column in a return variable, I suppose this may represent a breaking API change, and boxr should increment version number if it's completely removed?

I do think the easiest solution, for now, is to leave that as is and extend the return with the new variables. 

Regarding `file_version_id` vs `version_id`, I'm in favor of keeping things relatively consistent with the box API, but in my opinion it's more important to be internally consistent across functions in the boxr package.

2020-09-21 15:48 UTC, alexbrodersen commented
Here's what I get from grep for the list of where version_id vs file_version_id is used. I can update my PR to change this based on whatever is decided?

```
boxr__internal_get.R:63:      version_id <- versions$file_version_id[version_no]
boxr_file_versions.R:9:#' The returned `data.frame` contains a variable, `file_version_id`, 
boxr_file_versions.R:63:  colnames(d)[colnames(d) == "id"] <- "file_version_id"

boxr__internal_get.R:30:boxGet <- function(file_id, local_file, version_id = NULL, version_no = NULL,
boxr__internal_get.R:36:  if (!is.null(version_id) & !is.null(version_no)) {
boxr__internal_get.R:38:    stop("Only one of version_id and version_no may be supplied")
boxr__internal_get.R:41:  if (is.null(version_id) & !is.null(version_no)) {
boxr__internal_get.R:63:      version_id <- versions$file_version_id[version_no]
boxr__internal_get.R:67:  if (!is.null(version_id)) {
boxr__internal_get.R:68:    # If you have a version_id, check that it looks reasonable (11 digits)
boxr__internal_get.R:69:    version_id <- as.numeric(version_id)
boxr__internal_get.R:71:    if (!grepl("[[:digit:]]{11}", version_id))
boxr__internal_get.R:72:      stop("version_id must be an integer, 11 characters in length")
boxr__internal_get.R:79:        file_id, "/content", "?version=", version_id
boxr_file_versions.R:9:#' The returned `data.frame` contains a variable, `file_version_id`, 
boxr_file_versions.R:63:  colnames(d)[colnames(d) == "id"] <- "file_version_id"
boxr_read.R:56:box_read <- function(file_id, type = NULL, version_id = NULL, 
boxr_read.R:64:  req <- boxGet(file_id, local_file = temp_file, version_id = version_id, 
boxr_s3_classes.R:143:      version_id          = x$file_version$id %|0|% NA_character_,
boxr_upload_download.R:13:#' **`version_id`** or **`version_no`**.
boxr_upload_download.R:17:#' using the `version_id` parameter.
boxr_upload_download.R:24:#' [box_previous_versions()] to retrieve the `version_id`,
boxr_upload_download.R:32:#' @param version_id `character` or `numeric`, the `version_id` of the file.
boxr_upload_download.R:57:                   file_name = NULL, version_id = NULL, version_no = NULL,
boxr_upload_download.R:88:  req <- boxGet(file_id = file_id, version_id = version_id,
```

2020-09-21 16:17 UTC, ijlyttle commented
Hi @alexbrodersen,

I think we are on the same page here.

If I were starting the package from scratch, I might have chosen `file_version_id` to be better aligned with the Box API, but I think the right move is to stick with `version_id` here.

We do plan to change the version number, but I think it would be "rude" for the `version` variable to just disappear - I think we can just have both for now, and think about how to remove it down the road.

The PR is in good shape now - I plan to get #159 taken care of immediately, then come back with specific suggestions for this PR - none of which will be very big or surprising.

2020-09-23 21:36 UTC, nathancday commented
IMO if we keep `version` named as is and add `version_id` this is good to go. Maybe add a test for names exceptions.

The box web app also must be doing a similar version inference because it displays a v1, v2, v3, ... badge next to file names and in the version menu. I think we should continue to support both (human readable number and full ID) like `box_dl()` whenever possible. No reason `box_version` can't report both.

<img width="214" alt="Screen Shot 2020-09-23 at 5 32 06 PM" src="https://user-images.githubusercontent.com/808225/94072014-e410a400-fdc2-11ea-9415-3226abe1d256.png">
<img width="314" alt="Screen Shot 2020-09-23 at 5 32 27 PM" src="https://user-images.githubusercontent.com/808225/94072021-e5da6780-fdc2-11ea-9b15-5ca13b4ddf50.png">

2020-09-23 22:04 UTC, ijlyttle commented
Sounds good to me! I can provide some specific feedback here shortly.

2020-09-23 22:26 UTC, ijlyttle requested changes

2020-09-23 22:26 UTC, ijlyttle commented on R/boxr_s3_classes.R
> -      version             = as.numeric(x$etag) + 1,
Let's keep the `version` variable.

2020-09-23 22:26 UTC, ijlyttle commented on DESCRIPTION
> +    person("Alex", "Brodersen", role = "ctb")
Not related to this line, but it's in the neighborhood. 

Just a heads up that just before merging the PR, we will manually bump the version based on where we will be at the time. No action needed by you, just so you will not be surprised.

2020-09-23 22:26 UTC, ijlyttle commented on NEWS.md
> +* `box_ls()` provides the current `version_id` by default.
Can you add "(#181, @alexbrodersen)" after the end of the sentence?

2020-09-23 22:28 UTC, ijlyttle commented
@alexbrodersen, I hit the wrong button before I could summarize the review. 

I don't think there is too much to do, once you are done, I'll be happy to bump the version.

As @nathancday points out, it will be good to have a test, but I had a look at the test and it's not too user friendly, so I will be happy to add a test before merging.

2020-10-12 22:27 UTC, ijlyttle approved these changes

2020-10-12 22:34 UTC, ijlyttle commented
@alexbrodersen I'm doing some other work that will need to incorporate yours, so I hope it's OK that I made the requested changes.

@nathancday can you have a look to make sure what I've done is OK?

2020-10-13 23:42 UTC, nathancday reviewed
Returning `version_no` feels weird, the two identical columns. What about just `version` and `version_id`? Keep the legacy and add Alex's improvement for id

2020-10-14 00:03 UTC, ijlyttle commented
The legacy was already split; `box_read()` and `box_dl()` both currently use a `version_no` argument.

I prefer `version_no` to `version` as it is more distinct from `version_id`. I agree it's awkward to return both, but I think we would have to do that for backwards compatibility (small as that risk might seem).

2020-10-14 00:09 UTC, nathancday commented
Yea totally forgot about the existing split across args. Sounds good to have the weirdness of dupes for consistancy.

2020-10-14 00:10 UTC, merged

2020-10-14 00:14 UTC, ijlyttle commented
Thanks @alexbrodersen!